= Solution Patterns: Predict stock price trend using Red Hat Openshift AI
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

This solution pattern brings an architectural solution demonstrating how one can use machine learning to predict stock price. In this solution pattern, we will show the deployment of machine learning model using data science pipelines and how we can set up these pipelines.

*Contributors:* Gaurav Midha, Ritesh Shah

++++
 <br>
++++
[NOTE]
====
Solutions Patterns help you understand the art of the possible with Red Hat's portfolio, and not intended to be used as is for production environments. You are welcome to use any part of this solution pattern for your own workloads.
====
[#use-cases]
== Use cases

Common use cases that can be address with this architecture are:

- Build, train and deploy machine learning model using Red Hat OpenShift AI.
- Use S3 backend storage for storing the model.
- Create and run Data Science pipelines in Openshift. 
- Consume the model via REST endpoint through a python application deployed in OpenShift.

include::01-pattern.adoc[]
